---
# defaults file for apache2
apache2_http_default_port: 80
apache2_config_dir: "/etc/apache2"
apache2_config_file: "{{ apache2_config_dir }}/apache2.conf"
apache2_site_available: "{{ apache2_config_dir }}/sites-available"
apache2_mods_available_dir: "{{ apache2_config_dir }}/mods-available"
apache2_mods_enabled_dir: "{{ apache2_config_dir }}/mods-enabled"

# Apache2 modsecurity 
apache2_mod_security_base_dir: "/etc/modsecurity"
apache2_mod_security_config : 
    - { regexp: "^SecRuleEngine", value: "SecRuleEngine On" }
    - { regexp: "^SecRequestBodyAccess", value: "SecRequestBodyAccess On" }
    - { regexp: "^SecAuditEngine", value: "SecAuditEngine RelevantOnly" }
    - { regexp: "^SecDebugLogLevel", value: "SecDebugLogLevel 1" }
   
# Apache server status module
apache2_status_dir: "/var/www/status"
apache2_status_server_name: ""
apache2_status_server_alias: ""
apache2_status_require_ip: ""
apache2_status_require_host: ""
apache2_status_enable_authentication: True
apache2_server_admin: "root@admin"
apache2_status_auth_login: "EL1638EN"
apache2_status_auth_passowrd: "Mmdp-3325"

apache2_mods_disabled: []
apache2_mods_enabled:
  - rewrite.load
  - ssl.load
  - proxy.conf
  - proxy.load
  - proxy_http.load  

apache2_config_params:
    - { regexp: "^ServerTokens", value: "ServerTokens Prod" }
    - { regexp: "^ServerSignature", value: "ServerSignature Off" }
    - { regexp: "^MaxRequestWorkers", value: "MaxRequestWorkers 300" }
    - { regexp: "^KeepAlive", value: "KeepAlive On" }
    - { regexp: "^MaxKeepAliveRequests", value: "MaxKeepAliveRequests 100" }
    - { regexp: "^KeepAliveTimeout", value: "KeepAliveTimeout 15" }
    - { regexp: "^HostnameLookups", value: "HostnameLookups Off" }
    - { regexp: "^LogLevel", value: "LogLevel warn" }
    - { regexp: "^SetOutputFilter", value: "SetOutputFilter DEFLATE" }






