---
# tasks file for sonarqube

- name : Check sonarqube home directory exists
  stat:
    path: "{{ sonarqube_home }}"
  register: sonarqube_home_result

- name : include install file
  include: install.yml
  when: not sonarqube_home_result.stat.exists