---

###################
# Playbook to install jenkins master
###################
- hosts: jenkins_master
  become: yes
  roles:
    - { role: ssh, ssh_delete_obsolete_packages: True }
    - { role: git }
    - { role: jenkins_master, jenkins_network_interface: "enp0s8", jenkins_iptables_enabled: True }