---

###################
# Playbook to install jenkins slave
###################

- hosts: jenkins_slave
  become: yes
  tasks:
    - name: Create user on servers machine
      user:
        name: "{{ jenkins_user_name }}"
        comment: "{{ jenkins_user_comment }}"
        shell: /bin/bash
        password: "{{ jenkins_user_password }}"
        generate_ssh_key: no

    - name: Init ssh directory
      file:
        path: "/home/{{ jenkins_user_name }}/.ssh"
        owner: "{{ jenkins_user_name }}"
        group: "{{ jenkins_user_name }}"
        mode: 0700
        state: directory
        recurse: yes

    - name: Init public keys
      file:
        path: "/home/{{ jenkins_user_name }}/.ssh/authorized_keys"
        state: touch
        state: present
        mode: 0600
        owner: "{{ jenkins_user_name }}"
        group: "{{ jenkins_user_name }}"


- hosts: jenkins_slave
  become: yes
  roles:
    - { role: ssh, ssh_delete_obsolete_packages: True }
    - { role: git }
    - { role: openjdk8 }
    - { role: maven }
    - { role: gradle }