---

# Playbook d'installation d'une plateforme d'integration continue (pic).

###################
# Installation du jenkins master
###################
- hosts: jenkins_master
  become: yes
  roles:
    - { role: ssh, ssh_delete_obsolete_packages: True }
    - { role: git }
    - { role: jenkins_master, jenkins_network_interface: "enp0s8", jenkins_iptables_enabled: True }

##################
# Gestion de la clé publique de l'utilisateur jenkins
##################
- hosts: localhost
  become: yes
  tasks:
  - name: Retrieve jenkins user public key
    local_action: shell cat {{ jenkins_public_key_dir }}/id_rsa.pub
    register: public_key

  - name: set jenkins_public_key
    set_fact:
      jenkins_public_key: '{{ public_key.stdout }}'

  - name: Delete jenkins slave user private key
    local_action: shell file path="{{ jenkins_public_key_dir }}/id_rsa.pub" state=absent

##################
# Installation du slave jenkins
##################
- hosts: jenkins_slave
  become: yes
  roles:
    - { role: jenkins_slave_user, jenkins_public_key: "{{ hostvars['localhost']['jenkins_public_key'] }}" }
    - { role: ssh, ssh_delete_obsolete_packages: True }
    - { role: git }
    - { role: openjdk8 }
    - { role: maven }
    - { role: gradle }



##################
# Installation nexus - TODO
##################



##################
# Installation sonarqube - TODO
##################


##################
# Android - TODO
##################
# https://pamartinezandres.com/how-to-set-up-a-continuous-integration-server-for-android-development-ubuntu-jenkins-sonarqube-43c1ed6b08d3?gi=6503321539ae
# https://pamartinezandres.com/running-android-tests-on-cloud-devices-using-a-jenkins-ci-server-firebase-test-lab-amazon-device-b67cb4b16c40

