---

# Playbook d'installation d'une plateforme d'integration continue (pic).

##################
# Installation des outils communs
##################
- hosts: all
  become: yes
  roles:
    - { role: ssh, ssh_delete_obsolete_packages: True }
    - { role: git }

###################
# Installation du jenkins master
###################
- hosts: jenkins_master
  become: yes
  roles:
    - role: apache2
    - role: jenkins
      jenkins_iptables_enabled: True
      jenkins_network_interface: "enp0s8"
      jenkins_reverse_proxy_enabled: True
      jenkins_host_ip: 192.168.56.2
      jenkins_reverse_proxy_http_default_port: 80
      jenkins_reverse_proxy_server_name: "jenkins.davidson.fr"


##################
# Gestion de la clé publique de l'utilisateur jenkins
##################
- hosts: localhost
  become: yes
  tasks:
  - name: Retrieve jenkins user public key
    local_action: shell cat {{ jenkins_public_key_dir }}/id_rsa.pub
    register: public_key
    no_log: True

  - name: set jenkins_public_key
    set_fact:
      jenkins_public_key: '{{ public_key.stdout }}'
    no_log: True
    
  - name: Delete jenkins slave user private key
    local_action: file path="{{ jenkins_public_key_dir }}/id_rsa.pub" state=absent

##################
# Installation du slave jenkins
##################
- hosts: jenkins_slave
  become: yes
  roles:
    - { role: jenkins_slave_user, jenkins_public_key: "{{ hostvars['localhost']['jenkins_public_key'] }}", tags: ['jenkins_slave_user'] }
    - { role: openjdk8 }
    - { role: maven }
    - { role: gradle }


