---
# Taches de configuration du serveur Jenkins

- name: Copie des configs Maven
  template:
    src: hudson.tasks.Maven.xml.j2
    dest: "{{ jenkins_home }}/hudson.tasks.Maven.xml"
    owner: "{{ jenkins_user_name }}"
    group: "{{ jenkins_user_name }}"
    mode: 0640