---
# tasks file for jenkins_master

- include: install.yml

- include: settings.yml

- include: plugins.yml

- include: iptables.yml
  when: jenkins_iptables_enabled

- name: Restart Jenkins
  command: echo "Restart Jenkins"
  notify:
    - Restart Jenkins

- name: Add reverse proxy configuration
  include: reverse_proxy.yml
  when: jenkins_reverse_proxy_enabled

- name: Restart apache2
  command: echo "Restart apache2"
  notify:
    - Restart apache2
  when: jenkins_reverse_proxy_enabled