---
# tasks file for jenkins_master

- include: install.yml

- include: settings.yml

- include: plugins.yml

- include: ssh_config.yml

- include: maven_config.yml

- include: credentials.yml

- include: nodes.yml

- include: ansible.yml

- name: Restart Jenkins
  command: echo "Restart Jenkins"
  notify:
    - Restart Jenkins

- include: iptables.yml
  when: jenkins_iptables_enabled

- name: Add reverse proxy configuration
  include: reverse_proxy.yml
  notify:
    - Restart apache2
  when: jenkins_reverse_proxy_enabled