---
# tasks file for jenkins_master

- name: Setting Jenkins default port
  lineinfile:
    dest: "{{ jenkins_config_file }}"
    regexp: "^HTTP_PORT="
    line: "HTTP_PORT={{ jenkins_port }}"
    state: present

- name: Setting Jenkins options
  lineinfile:
    dest: "{{ jenkins_config_file }}"
    regexp: "^JAVA_ARGS="
    line: "JAVA_ARGS={{ jenkins_options }}"
    state: present

- name: Setting Jenkins default file owner and group
  file:
    path: "{{ jenkins_config_file }}"
    owner: root
    group: root
    mode: 0644

- name: Immediately restart Jenkins.
  service: 
    name: jenkins
    state: restarted

- name: Delete Jenkins security init scripts after first starting.
  file:
    path: "{{ jenkins_home }}/init.groovy.d/basic-security.groovy"
    state: absent

- name: Disable security - copy script to remote host
  template:
    src: disable-security.python.j2
    dest: "/tmp/disable-security.python"
    owner: "{{ jenkins_user_name }}"
    group: "{{ jenkins_user_name }}"
    mode: 0755

- name: Execute script to disable security
  command: >
    python /tmp/disable-security.python

- name: Set the TCP port for JNLP agents
  lineinfile:
    path: "{{ jenkins_home }}/config.xml"
    regexp: "^(\\s*)<slaveAgentPort>"
    line: "\\1<slaveAgentPort>0</slaveAgentPort>"
    backrefs: yes

- name: Update file owner/group and rights
  file:
    path: "{{ jenkins_home }}/config.xml"
    owner: "{{ jenkins_user_name }}"
    group: "{{ jenkins_user_name }}"
    mode: 0644

- name: Delete groovy file
  file:
    path: "/tmp/disable-security.python"
    state: absent

- name: Setting Jenkins CLI enabled
  copy:
    src: jenkins.CLI.xml
    dest: "{{ jenkins_cli_file }}"
    owner: "{{ jenkins_user_name }}"
    group: "{{ jenkins_user_name }}"
    mode: 0644

- name: Restart Jenkins
  command: echo "Restart Jenkins"
  notify:
    - Restart Jenkins

- name: Wait 150 seconds for restart jenkins.
  wait_for:
    timeout: 150