---
# tasks file to install apache2 and aditionnal modules

- name: Update apt cache.
  apt:
    update_cache: yes

- name: Install Apache.
  apt:
    pkg: "{{ item }}"
    state: present
  with_items:
    - "apache2"
    - "apache2-utils"

- name: Install additionnal modules Apache.
  apt:
    pkg: "{{ item }}"
    state: present
  with_items:
    - "libapache2-mod-jk"
    - "libapache2-mod-security2"