---
# tasks file for apache2

- include_tasks: install.yml

- include_tasks: backup.yml

- include_tasks: config.yml

- include_tasks: modsecurity.yml

- include_tasks: status.yml

- name: Restart apache2
  command: echo "Restart apache2"
  notify:
    - Restart apache2