---

- name: Install archive tools
  apt:
    name: "{{ item }}"
    state: latest
  with_items:
    - "tar"
    - "unzip"

- name: Create maven directory
  file:
    path: "{{ maven_install_directory }}"
    state: directory
    owner: root
    group: root
    recurse: yes

- name: Download, decompress and delete maven archive
  unarchive:
    src: "{{ maven_download_archive_url }}"
    dest: "{{ maven_install_directory }}/"
    remote_src: True

- name: Update maven directory
  file:
    path: "{{ maven_install_directory }}"
    state: directory
    owner: root
    group: root
    recurse: yes

- name: Add/Update environments variables
  blockinfile:
    dest: "/etc/profile"
    insertafter: EOF
    block: |
      # Maven Home
      M2_HOME="{{ maven_home }}"
      export M2_HOME
      # Update PATH
      PATH=$PATH:"$M2_HOME/bin"
      export PATH
    state: present

- name: Relaod environments variables
  shell: . /etc/profile

