---
# tasks file for maven

- name: Get Maven version installed on the machin
  shell: "{{ maven_home }}/bin/mvn --version 2>&1"
  register: maven_version_result
  ignore_errors: True

- include: install.yml
  when: (maven_version_result|failed) or (maven_version not in maven_version_result.stdout)