---
# tasks file for ssh

# https://www.ssi.gouv.fr/uploads/2014/01/NT_OpenSSH.pdf. Rule R2 & R3
- name: Delete obsolete packages (Telnet, Rsh and Rlogin)
  apt:
    pkg: "{{ item }}"
    state: absent
  with_items :
    - "telnet"
    - "rshd"
    - "rlogin"
  when: ssh_delete_obsolete_packages

- name: Backup config file
  include: backup.yml

- name : Init banner file with little information
  command: echo "{{ ssh_banner_information }}" > "{{ item }}"
  with_items:  "{{ ssh_issue_files }}"

- name : Init motd file with warning message
  copy:
    src: motd
    dest: "{{ ssh_motd_file }}"
    owner: root
    group: root
    mode: 0644

- name : Init timeout for unactive user
  blockinfile:
    dest: "{{ ssh_profile_file }}"
    insertafter: EOF
    block: |
        TMOUT={{ ssh_tmout }}
        HISTSIZE={{ ssh_histsize }}
        HISTFILESIZE={{ ssh_histfilesize }}
        export TMOUT HISTSIZE HISTFILESIZE
    owner: root
    group: root
    mode: 0644

- name: Install openssh-server package
  apt:
    pkg: "{{ ssh_package }}"
    state: present

- name: Change the banner
  copy:
    src: banner
    dest: "{{ ssh_banner_file }}"
    owner: root
    group: root
    mode: 0644

- name : Check config file backup exists
  stat:
    path: "{{ ssh_config_file }}.backup"
  register: ssh_config_backup_file

- name : make a backup for ssh config file
  copy:
    src: "{{ ssh_config_file }}"
    dest: "{{ ssh_config_file }}.backup"
    owner: root
    group: root
    mode: 0644
    remote_src: yes
  when: not ssh_config_backup_file.stat.exists

- name: Change the config of ssh
  lineinfile:
    dest: "{{ ssh_config_file }}"
    regexp: "{{ item.regexp }}"
    line: "{{ item.value }}"
    owner: root
    group: root
    mode: 0644
    state: present
  with_items: "{{ ssh_config }}"

# https://www.ssi.gouv.fr/uploads/2014/01/NT_OpenSSH.pdf. Rule R15
- name: Add ETM encrypt for ssh version >=6.3
  lineinfile:
    dest: "{{ ssh_config_file }}"
    line: "{{ ssh_macs_etm }}"
    owner: root
    group: root
    mode: 0644
  when: ssh_version >= ssh_version_support_etm

- name: Add hmac-sha1 for ssh version < 6.3
  lineinfile:
    dest: "{{ ssh_config_file }}"
    line: "{{ ssh_macs_old }}"
    owner: root
    group: root
    mode: 0644
  when: ssh_version < ssh_version_support_etm

- meta: flush_handlers