---
# tasks file for nexus

- name : Check nexus home directory exists
  stat:
    path: "{{ nexus_home }}"
  register: nexus_home_result

- name : include install file
  include: install.yml
  when: not nexus_home_result.stat.exists