---
# tasks file for reverse proxy nexus

- name: Copy virtualhost file
  template:
    src: vhosts_nexus_apache2.j2
    dest: "/etc/apache2/sites-available/nexus.conf"
    owner: root
    group: root

- name: Enable Virtualhost for nexus.
  file:
    src: "/etc/apache2/sites-available/nexus.conf"
    dest: "/etc/apache2/sites-enabled/nexus.conf"
    state: link
    owner: root
    group: root
    mode: 0777
  notify:
  - Restart apache2
