---

- name: Install Python and pip tools
  apt:
    name: "{{ item }}"
    state: present
  with_items:
    - vim
    - python3
    - python3-dev
    - python3-pip

- name: Install pip
  command: >
    easy_install3 pip

- name: Install Ansible tools
  pip:
    name: "{{ item }}"
    state: present
  with_items:
    - ansible
    - virtualenv
    - virtualenvwrapper