---
# Variable setup.
# - name: Include OS-Specific variables
#   include_vars: "{{ ansible_os_family }}.yml"

- include_tasks: setup-Debian.yml

# Configure Jenkins init settings.
- include_tasks: settings.yml

# Make sure Jenkins starts, then configure Jenkins.
- name: Ensure Jenkins is started and runs on startup.
  service: 
    name: jenkins
    state: started
    enabled: yes

- name: Wait for Jenkins to start up before proceeding.
  shell: "curl -D - --silent --max-time 5 http://{{ jenkins_hostname }}:{{ jenkins_http_port }}{{ jenkins_url_prefix }}/cli/"
  register: result
  until: (result.stdout.find("403 Forbidden") != -1) or (result.stdout.find("200 OK") != -1) and (result.stdout.find("Please wait while") == -1)
  retries: "{{ jenkins_connection_retries }}"
  delay: "{{ jenkins_connection_delay }}"
  changed_when: false
  check_mode: no

- name: Get the jenkins-cli jarfile from the Jenkins server.
  get_url:
    url: "http://{{ jenkins_hostname }}:{{ jenkins_http_port }}{{ jenkins_url_prefix }}/jnlpJars/jenkins-cli.jar"
    dest: "{{ jenkins_jar_location }}"
  register: jarfile_get
  until: "'OK' in jarfile_get.msg or 'file already exists' in jarfile_get.msg"
  retries: 5
  delay: 10
  check_mode: no

- name: Remove Jenkins security init scripts after first startup.
  file:
    path: "{{ jenkins_home }}/init.groovy.d/basic-security.groovy"
    state: absent

# Update Jenkins and install configured plugins.
- include_tasks: plugins.yml

# Config SSH
- include_tasks: ssh-config.yml

# Gestion de la configuration de Maven
- include_tasks: maven-config.yml

# Gestion des credentials de j'utilisateur Jenkins
- include_tasks: credentials.yml

# Ajout des noeuds-slaves
- include_tasks: nodes.yml

# Installation d'ansible
- include_tasks: ansible.yml

- include_tasks: iptables.yml
  when: jenkins_iptables_enabled

- name: Add reverse proxy configuration
  include_tasks: reverse-proxy.yml
  notify:
    - restart apache2
  when: jenkins_reverse_proxy_enabled
